route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            api_url: 'https://hooks.slack.com/services/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'
